enum class State
{
    INIT,
    TEST,
    TEST_RUNNING,
    CAPUTRE_IMAGE,
    FEATURE_DETECT,
    COORDINATE_CALCULATION,
    CAPUTRE_IMAGE_RUNNING,
    FEATURE_DETECT_RUNNING,
    COORDINATE_CALCULATION_RUNNING,
    FINISHED
};