enum class State
{
    INIT,
    TEST,
    TEST_RUNNING,
    CAPUTRE_IMAGE,
    FEATURE_DETECT,
    MATCHING,
    MATCHING_RUNNING,
    MAPPING,
    MAPPING_RUNNING,
    CAPUTRE_IMAGE_RUNNING,
    FEATURE_DETECT_RUNNING,
    FINISHED
};